### PR TITLE
Prepare for Jenkins and eventually clickable, disabling tests for now and a few small optimizations

### PR DESCRIPTION
**Pull request by Flohack74**
This should bring the printing app to life (and we should add it to the future roofs images)

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Huh? Why does the pr job fail but the branch not? Things seem to go south after https://ci.ubports.com/blue/organizations/jenkins/ubuntu-printing-app/detail/PR-2/2/pipeline#step-40-log-393. The error occurs in both jobs, but in the branch job it just goes on to install the dependencies, in the PR-Merge it just dies. What's going on here?

**Comment by Flohack74** [comment]
I dont know, I did change nothing after the feature branch was green, just merged & PRd

**Comment by Flohack74** [comment]
After this is working and we merge, please add to rootfs and also update https://github.com/ubports/ubuntu-touch/issues/593

**Comment by NeoTheThird** [comment]
Any ideas @mariogrip?

**Comment by mariogrip** [comment]
ah i see pr-2 has had an ui-toolkit built for it before... so it tries to use that one. this can just be merged. We need to have the "delete packages after 2 months or after pr closes" function before this can be fixed so its a infrastructure problem, not a build error.

**Comment by Flohack74** [comment]
Alright, its green again! I will add it to the image now...

**Pull request merged**
